export const LOGIN_USER_START = Symbol('LOGIN_USER_START');
export const LOGIN_USER_SUCCESS = Symbol('LOGIN_USER_SUCCESS');
export const LOGIN_USER_FAILURE = Symbol('LOGIN_USER_FAILURE');

export const ADDING_NEWS_START = Symbol('ADDING_NEWS_START');
export const ADDING_NEWS_SUCCESS = Symbol('ADDING_NEWS_SUCCESS');
export const ADDING_NEWS_FAILURE = Symbol('ADDING_NEWS_FAILURE');

export const GET_USER_DATA_START = Symbol('GET_USER_DATA_START');
export const GET_USER_DATA_SUCCESS = Symbol('GET_USER_DATA_SUCCESS');
export const GET_USER_DATA_FAILURE = Symbol('GET_USER_DATA_FAILURE');

export const UPDATE_USER_DATA_START = Symbol('UPDATE_USER_DATA_START');
export const UPDATE_USER_DATA_SUCCESS = Symbol('UPDATE_USER_DATA_SUCCESS');
export const UPDATE_USER_DATA_FAILURE = Symbol('UPDATE_USER_DATA_FAILURE');

export const START_LOGIN = Symbol('START_LOGIN');
export const SUCCESS_LOGIN = Symbol('SUCCESS_LOGIN');
export const FAILURE_LOGIN = Symbol('FAILURE_LOGIN'); 

export const REQUEST_PENDING = 'REQUEST_PENDING';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const REQUEST_SUCCEDED = 'REQUEST_SUCCEDED';


export const START_UPLOAD = 'START_UPLOAD';
export const SUCCESS_UPLOAD = 'SUCCESS_UPLOAD'; 
export const FAILURE_UPLOAD = 'FAILURE_UPLOAD';

export const ADDING_PROJECT_START = Symbol('ADDING_PROJECT_START');
export const ADDING_PROJECT_SUCCESS = Symbol('ADDING_PROJECT_SUCCESS');
export const ADDING_PROJECT_FAILURE = Symbol('ADDING_PROJECT_FAILURE');
