'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var PROJECTS_FETCH_START = exports.PROJECTS_FETCH_START = Symbol('PROJECTS_FETCH_START');
var PROJECTS_FETCH_SUCCESS = exports.PROJECTS_FETCH_SUCCESS = Symbol('PROJECTS_FETCH_SUCCESS');
var PROJECTS_FETCH_FAILURE = exports.PROJECTS_FETCH_FAILURE = Symbol('PROJECTS_FETCH_FAILURE');

var GET_PROJECTS_START = exports.GET_PROJECTS_START = Symbol('GET_PROJECTS_START');
var GET_PROJECTS_SUCCESS = exports.GET_PROJECTS_SUCCESS = Symbol('GET_PROJECTS_SUCCESS');
var GET_PROJECTS_FAILURE = exports.GET_PROJECTS_FAILURE = Symbol('GET_PROJECTS_FAILURE');

var GET_PROJECT_DATA_START = exports.GET_PROJECT_DATA_START = Symbol('GET_PROJECT_DATA_START');
var GET_PROJECT_DATA_SUCCESS = exports.GET_PROJECT_DATA_SUCCESS = Symbol('GET_PROJECT_DATA_SUCCESS');
var GET_PROJECT_DATA_FAILURE = exports.GET_PROJECT_DATA_FAILURE = Symbol('GET_PROJECT_DATA_FAILURE');

var GET_NEWS_DATA_START = exports.GET_NEWS_DATA_START = Symbol('GET_NEWS_DATA_START');
var GET_NEWS_DATA_SUCCESS = exports.GET_NEWS_DATA_SUCCESS = Symbol('GET_NEWS_DATA_SUCCESS');
var GET_NEWS_DATA_FAILURE = exports.GET_NEWS_DATA_FAILURE = Symbol('GET_NEWS_DATA_FAILURE');

var GET_NEWS_START = exports.GET_NEWS_START = Symbol('GET_NEWS_START');
var GET_NEWS_SUCCESS = exports.GET_NEWS_SUCCESS = Symbol('GET_NEWS_SUCCESS');
var GET_NEWS_FAILURE = exports.GET_NEWS_FAILURE = Symbol('GET_NEWS_FAILURE');

var ADD_COMMENT_START = exports.ADD_COMMENT_START = Symbol('ADD_COMMENT_START');
var ADD_COMMENT_SUCCESS = exports.ADD_COMMENT_SUCCESS = Symbol('ADD_COMMENT_SUCCESS');
var ADD_COMMENT_FAILURE = exports.ADD_COMMENT_FAILURE = Symbol('ADD_COMMENT_FAILURE');

var GET_COMMENT_START = exports.GET_COMMENT_START = Symbol('GET_COMMENT_START');
var GET_COMMENT_SUCCESS = exports.GET_COMMENT_SUCCESS = Symbol('GET_COMMENT_SUCCESS');
var GET_COMMENT_FAILURE = exports.GET_COMMENT_FAILURE = Symbol('GET_COMMENT_FAILURE');