export const PROJECTS_FETCH_START = Symbol('PROJECTS_FETCH_START');
export const PROJECTS_FETCH_SUCCESS = Symbol('PROJECTS_FETCH_SUCCESS');
export const PROJECTS_FETCH_FAILURE = Symbol('PROJECTS_FETCH_FAILURE');

