export const PROJECTS_FETCH_START = Symbol('PROJECTS_FETCH_START');
export const PROJECTS_FETCH_SUCCESS = Symbol('PROJECTS_FETCH_SUCCESS');
export const PROJECTS_FETCH_FAILURE = Symbol('PROJECTS_FETCH_FAILURE');


export const GET_PROJECTS_START = Symbol('GET_PROJECTS_START');
export const GET_PROJECTS_SUCCESS = Symbol('GET_PROJECTS_SUCCESS');
export const GET_PROJECTS_FAILURE = Symbol('GET_PROJECTS_FAILURE');

export const GET_PROJECT_DATA_START = Symbol('GET_PROJECT_DATA_START');
export const GET_PROJECT_DATA_SUCCESS = Symbol('GET_PROJECT_DATA_SUCCESS');
export const GET_PROJECT_DATA_FAILURE = Symbol('GET_PROJECT_DATA_FAILURE');


export const GET_NEWS_DATA_START = Symbol('GET_NEWS_DATA_START');
export const GET_NEWS_DATA_SUCCESS = Symbol('GET_NEWS_DATA_SUCCESS');
export const GET_NEWS_DATA_FAILURE = Symbol('GET_NEWS_DATA_FAILURE');


export const GET_NEWS_START = Symbol('GET_NEWS_START');
export const GET_NEWS_SUCCESS = Symbol('GET_NEWS_SUCCESS');
export const GET_NEWS_FAILURE = Symbol('GET_NEWS_FAILURE');


export const ADD_COMMENT_START = Symbol('ADD_COMMENT_START');
export const ADD_COMMENT_SUCCESS = Symbol('ADD_COMMENT_SUCCESS');
export const ADD_COMMENT_FAILURE = Symbol('ADD_COMMENT_FAILURE');

export const GET_COMMENT_START = Symbol('GET_COMMENT_START');
export const GET_COMMENT_SUCCESS = Symbol('GET_COMMENT_SUCCESS');
export const GET_COMMENT_FAILURE = Symbol('GET_COMMENT_FAILURE');
